name: blueprint_system
description: A flutter library that creates blueprint widgets with nodes (child widgets) that may be added to them. These nodes can be moved, resized, and modified.
version: 0.1.2
homepage: https://salah-rashad.github.io/blueprint_system
repository: https://github.com/salah-rashad/blueprint_system

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  intl: ^0.17.0
  uuid: ^3.0.6
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
