name: Deploy Example Project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Build and deploy Flutter web app
        uses: Antinna/fa@v1.0.0
        id: build
        with:
          release: true
          gh_pages: true
          webRenderer: auto
          baseHref: "/"
          workingDir: ./example
