name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '2.x' # any version
      - name: Build web app
        run: flutter build web
        working-directory: ./example
      - name: Deploy to GitHub Pages
        uses: AlienKevin/flutter-gh-pages@v11
        with:
          targetBranch: gh-pages
          workingDir: ./example
          baseHref: /blueprint_system/
