
    
  
name: Deploy Example Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: erickzanardo/flutter-gh-pages@v6
        with:
          workingDir: example
