on:
  push:
    branches:
    - master

name: Deploy Example Project
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Pinky Flutter
        uses: rexthecoder/Pinky@v2.0.0
        with:
          web: true
  
  
